"""唯一 HTTP 注册表；文档与运行分派共用相同方法、路径和领域适配。"""

ROUTES = {
    ('GET', '/api/label-plan/revert-preview'): '_ai_review_get',
    ('POST', '/api/label-plan/revert'): '_label_plan_revert',
    ('GET', '/api/ai-review/items'): '_ai_review_get',
    ('GET', '/api/ai-review/detail'): '_ai_review_get',
    ('GET', '/api/ai-review/counts'): '_ai_review_get',
    ('POST', '/api/ai-review/update'): '_ai_review_post',
    ('POST', '/api/ai-review/decide'): '_ai_review_post',
    ('GET', '/'): '_core_get',
    ('GET', '/annotate'): '_annotate_get',
    ('GET', '/api/agent/conversation'): '_agent_get',
    ('GET', '/api/agent/conversations'): '_agent_get',
    ('GET', '/api/agent/events'): '_agent_get',
    ('GET', '/api/agent/practice'): '_agent_get',
    ('GET', '/api/agent/status'): '_agent_get',
    ('GET', '/api/analytics'): '_core_get',
    ('GET', '/api/annotate/export'): '_annotate_get',
    ('GET', '/api/annotate/images'): '_annotate_get',
    ('GET', '/api/annotate/raw'): '_annotate_get',
    ('GET', '/api/annotate/stats'): '_annotate_get',
    ('GET', '/api/auth/session'): '_auth_status',
    ('GET', '/api/board'): '_core_get',
    ('GET', '/api/boards'): '_core_get',
    ('GET', '/api/config'): '_core_get',
    ('GET', '/api/drafts/counts'): '_drafts_get',
    ('GET', '/api/drafts/image'): '_drafts_get',
    ('GET', '/api/drafts/item'): '_drafts_get',
    ('GET', '/api/drafts/job'): '_drafts_get',
    ('GET', '/api/drafts/list'): '_drafts_get',
    ('GET', '/api/entry-background'): '_core_get',
    ('GET', '/api/export-review'): '_core_get',
    ('GET', '/api/history'): '_core_get',
    ('GET', '/api/history/detail'): '_core_get',
    ('GET', '/api/image'): '_core_get',
    ('GET', '/api/inbox/dataset/export'): '_inbox_get',
    ('GET', '/api/inbox/dataset/stats'): '_inbox_get',
    ('GET', '/api/inbox/item'): '_inbox_get',
    ('GET', '/api/inbox/items'): '_inbox_get',
    ('GET', '/api/inbox/job'): '_inbox_get',
    ('GET', '/api/inbox/raw'): '_inbox_get',
    ('GET', '/api/inbox/slice-plan'): '_inbox_get',
    ('GET', '/api/labels'): '_core_get',
    ('GET', '/api/ledger/verify'): '_core_get',
    ('GET', '/api/mcp/exports/download'): '_mcp_get',
    ('GET', '/api/mcp/keys'): '_mcp_get',
    ('GET', '/api/mcp/operations/detail'): '_mcp_get',
    ('GET', '/api/optimize/job'): '_core_get',
    ('GET', '/api/optimize/summary'): '_core_get',
    ('GET', '/api/question'): '_core_get',
    ('GET', '/api/question/content/history'): '_core_get',
    ('GET', '/api/question/content/version'): '_core_get',
    ('GET', '/api/question/raw'): '_core_get',
    ('GET', '/api/recommend'): '_core_get',
    ('GET', '/api/report/view'): '_core_get',
    ('GET', '/api/reports'): '_core_get',
    ('GET', '/api/runtime/records'): '_core_get',
    ('GET', '/api/runtime/records/detail'): '_core_get',
    ('GET', '/api/scan'): '_core_get',
    ('GET', '/api/session'): '_core_get',
    ('GET', '/api/sessions'): '_core_get',
    ('GET', '/api/source/export'): '_core_get',
    ('GET', '/api/stats'): '_core_get',
    ('GET', '/api/status'): '_core_get',
    ('GET', '/api/taxonomy'): '_core_get',
    ('GET', '/api/trainpanel/audit'): '_trainpanel_get',
    ('GET', '/api/trainpanel/audit-image'): '_trainpanel_get',
    ('GET', '/api/trainpanel/audits'): '_trainpanel_get',
    ('GET', '/api/trainpanel/manager'): '_trainpanel_get',
    ('GET', '/api/trainpanel/overlay'): '_trainpanel_get',
    ('GET', '/api/trainpanel/overview'): '_trainpanel_get',
    ('GET', '/api/trainpanel/reviews'): '_trainpanel_get',
    ('GET', '/api/trainpanel/run'): '_trainpanel_get',
    ('GET', '/api/trainpanel/service'): '_trainpanel_get',
    ('GET', '/api/tree'): '_core_get',
    ('GET', '/index.html'): '_core_get',
    ('GET', '/login'): '_core_get',
    ('GET', '/m'): '_inbox_get',
    ('GET', '/train'): '_trainpanel_get',
    ('POST', '/api/agent/abort'): '_agent_post',
    ('POST', '/api/agent/confirm'): '_agent_post',
    ('POST', '/api/agent/conversation/create'): '_agent_post',
    ('POST', '/api/agent/conversation/delete'): '_agent_post',
    ('POST', '/api/agent/message'): '_agent_post',
    ('POST', '/api/agent/practice/progress'): '_agent_post',
    ('POST', '/api/agent/practice/start'): '_agent_post',
    ('POST', '/api/agent/run/revert'): '_agent_post',
    ('POST', '/api/agent/test'): '_agent_post',
    ('POST', '/api/ai-recognize'): '_questions_post',
    ('POST', '/api/annotate/delete'): '_annotate_post',
    ('POST', '/api/annotate/save'): '_annotate_post',
    ('POST', '/api/annotate/upload-refs'): '_annotate_post',
    ('POST', '/api/annotate/upload'): '_annotate_post',
    ('POST', '/api/auth/activity'): '_auth_post',
    ('POST', '/api/auth/disable'): '_auth_post',
    ('POST', '/api/auth/login'): '_auth_login',
    ('POST', '/api/auth/logout'): '_auth_post',
    ('POST', '/api/auth/pin'): '_auth_post',
    ('POST', '/api/auth/warning-ack'): '_auth_post',
    ('POST', '/api/backup/export'): '_do_post_routes',
    ('POST', '/api/backup/import'): '_do_post_routes',
    ('POST', '/api/backup/restore'): '_do_post_routes',
    ('POST', '/api/board/create'): '_boards_post',
    ('POST', '/api/board/delete'): '_boards_post',
    ('POST', '/api/board/duplicate'): '_boards_post',
    ('POST', '/api/board/folder/create'): '_boards_post',
    ('POST', '/api/board/folder/delete'): '_boards_post',
    ('POST', '/api/board/folder/update'): '_boards_post',
    ('POST', '/api/board/items/add'): '_boards_post',
    ('POST', '/api/board/items/remove'): '_boards_post',
    ('POST', '/api/board/move'): '_boards_post',
    ('POST', '/api/board/printed'): '_boards_post',
    ('POST', '/api/board/printed/reset'): '_boards_post',
    ('POST', '/api/board/update'): '_boards_post',
    ('POST', '/api/config'): '_do_post_routes',
    ('POST', '/api/confirm-schedule'): '_learning_post',
    ('POST', '/api/create'): '_questions_post',
    ('POST', '/api/drafts/boxes'): '_drafts_post',
    ('POST', '/api/drafts/cleanup'): '_drafts_post',
    ('POST', '/api/drafts/commit'): '_drafts_post',
    ('POST', '/api/drafts/detect'): '_drafts_post',
    ('POST', '/api/drafts/discard'): '_drafts_post',
    ('POST', '/api/drafts/extract'): '_drafts_post',
    ('POST', '/api/drafts/image/train'): '_drafts_post',
    ('POST', '/api/drafts/update'): '_drafts_post',
    ('POST', '/api/entry-background'): '_do_post_routes',
    ('POST', '/api/export'): '_learning_post',
    ('POST', '/api/feedback'): '_learning_post',
    ('POST', '/api/history/review/replace'): '_history_post',
    ('POST', '/api/history/review/restore'): '_history_post',
    ('POST', '/api/history/review/retract'): '_history_post',
    ('POST', '/api/history/session/restore'): '_history_post',
    ('POST', '/api/history/session/retract'): '_history_post',
    ('POST', '/api/history/state/restore'): '_history_post',
    ('POST', '/api/inbox/cleanup'): '_inbox_post',
    ('POST', '/api/inbox/commit'): '_inbox_post',
    ('POST', '/api/inbox/crops'): '_inbox_post',
    ('POST', '/api/inbox/discard'): '_inbox_post',
    ('POST', '/api/inbox/item/reset'): '_inbox_post',
    ('POST', '/api/inbox/item/update'): '_inbox_post',
    ('POST', '/api/inbox/jobs'): '_inbox_post',
    ('POST', '/api/inbox/upload-refs'): '_inbox_post',
    ('POST', '/api/inbox/upload'): '_inbox_post',
    ('POST', '/api/label/delete'): '_questions_post',
    ('POST', '/api/label/merge'): '_questions_post',
    ('POST', '/api/label/save'): '_questions_post',
    ('POST', '/api/mcp/keys'): '_mcp_post',
    ('POST', '/api/mcp/keys/revoke'): '_mcp_post',
    ('POST', '/api/mcp/keys/update'): '_mcp_post',
    ('POST', '/api/mcp/operations/decide'): '_mcp_post',
    ('POST', '/api/optimize/compress'): '_do_post_routes',
    ('POST', '/api/optimize/scan'): '_do_post_routes',
    ('POST', '/api/question/content/restore'): '_questions_post',
    ('POST', '/api/question/delete'): '_questions_post',
    ('POST', '/api/question/labels'): '_questions_post',
    ('POST', '/api/question/markdown'): '_questions_post',
    ('POST', '/api/question/move'): '_questions_post',
    ('POST', '/api/question/resume'): '_questions_post',
    ('POST', '/api/question/suspend'): '_questions_post',
    ('POST', '/api/questions/labels'): '_questions_post',
    ('POST', '/api/report/create'): '_do_post_routes',
    ('POST', '/api/report/delete'): '_do_post_routes',
    ('POST', '/api/restart'): '_do_post_routes',
    ('POST', '/api/scan'): '_do_post_routes',
    ('POST', '/api/schedule'): '_learning_post',
    ('POST', '/api/session/bind'): '_learning_post',
    ('POST', '/api/session/delete'): '_learning_post',
    ('POST', '/api/trainpanel/control'): '_trainpanel_post',
    ('POST', '/api/trainpanel/review'): '_trainpanel_post',
    ('POST', '/api/trainpanel/try'): '_trainpanel_post',
    ('POST', '/api/uploads/chunk'): '_uploads_post',
    ('POST', '/api/uploads/complete'): '_uploads_post',
    ('POST', '/api/uploads/start'): '_uploads_post',
    ('POST', '/api/workspace/scan'): '_do_post_routes',
}
PREFIXES = {("GET", "/assets/"): "_core_get"}


def target(method, path):
    exact = ROUTES.get((method, path))
    if exact:
        return exact
    return next((handler for (verb, prefix), handler in PREFIXES.items() if verb == method and path.startswith(prefix)), None)


def dispatch(handler, method, path, params=None):
    name = target(method, path)
    if name is None:
        handler._json({"status": "error", "msg": "接口不存在"}, 404)
        return
    fn = getattr(handler, name)
    if name in ("_auth_status", "_auth_login"):
        return fn()
    return fn(path, params or {}) if method == "GET" else fn(path)
